language: node_js
node_js:
  - "18"

addons:
  chrome: stable

cache:
  directories:
     - ./flying-track-ft/node_modules

install:
  - npm install

script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadless